name: uz_travel
description: "A new Flutter project."


publish_to: 'none'













version: 1.0.0+1

environment:
  sdk: ^3.8.1







dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.0
  firebase_auth: ^5.6.1
  flutter_screenutil: ^5.9.3
  flutter_gen_runner: ^5.10.0
  vector_graphics: ^1.1.19
  cloud_firestore: ^5.6.11
  provider: ^6.1.5
  flutter_svg: ^2.2.0
  easy_localization: ^3.0.7+1
  google_sign_in: ^7.1.0
  calendar_date_picker2: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter






  flutter_lints: ^6.0.0
  build_runner: ^2.5.4





flutter:


  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/fonts/
    - assets/images/
    - assets/lang/

  fonts:
    - family: Geometr415 Blk BT
      fonts:
        - asset: assets/fonts/GIL_____.ttf
        - asset: assets/fonts/ufonts.com_geometr415-blk-bt-black.ttf



    - family: Gilroy
      fonts:
        - asset: assets/fonts/GIL_____.ttf
flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    image: true
    flutter_svg: true
    # lottie: true # Uncomment if use Lottie
  assets:
    enabled: true
  fonts:
    enabled: true



































