// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDomMRJqm7xpxf601pPbiYsvNVGuLzJuhU',
    appId: '1:672973784855:web:04b75a07389290c4571952',
    messagingSenderId: '672973784855',
    projectId: 'uztravel-5f6ff',
    authDomain: 'uztravel-5f6ff.firebaseapp.com',
    storageBucket: 'uztravel-5f6ff.firebasestorage.app',
    measurementId: 'G-CC03T0PK8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDDyOvJ30NkPQ-7PMW2aCy3c12rDzJc1Q',
    appId: '1:672973784855:android:7dca5c20f2119911571952',
    messagingSenderId: '672973784855',
    projectId: 'uztravel-5f6ff',
    storageBucket: 'uztravel-5f6ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_S8Y8kBoxcfV76NZwUUNoVM9TKt0EMCA',
    appId: '1:672973784855:ios:314d2ea5c01b76de571952',
    messagingSenderId: '672973784855',
    projectId: 'uztravel-5f6ff',
    storageBucket: 'uztravel-5f6ff.firebasestorage.app',
    iosBundleId: 'uz.uztravel.uzTravel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_S8Y8kBoxcfV76NZwUUNoVM9TKt0EMCA',
    appId: '1:672973784855:ios:314d2ea5c01b76de571952',
    messagingSenderId: '672973784855',
    projectId: 'uztravel-5f6ff',
    storageBucket: 'uztravel-5f6ff.firebasestorage.app',
    iosBundleId: 'uz.uztravel.uzTravel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDomMRJqm7xpxf601pPbiYsvNVGuLzJuhU',
    appId: '1:672973784855:web:b5caaa05af1211a5571952',
    messagingSenderId: '672973784855',
    projectId: 'uztravel-5f6ff',
    authDomain: 'uztravel-5f6ff.firebaseapp.com',
    storageBucket: 'uztravel-5f6ff.firebasestorage.app',
    measurementId: 'G-909VZ0RYPT',
  );
}
